export const ONAUTHHANDLER = 'ONAUTHHANDLER';
export const SIGNINHANDLER = 'SIGNINHANDLER';
export const SIGNUPHANDLER = 'SIGNUPHANDLER';
export const SIGNOUTHANDLER = 'SIGNOUTHANDLER';
export const SIGNUPCLICKHANDLER = 'SIGNUPCLICKHANDLER';